version: '3.8'

services:
  pack-calculator:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PACK_SIZES=250,500,1000,2000,5000
    restart: unless-stopped